webpage/config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  get 'welcome/index'

  root 'welcome#index'

end

webpage/app/models/review.rb
class Review < ActiveRecord::Base
end

webpage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webpage/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:location, :description, :video_url, :picture_url, :comment, :rating)
    end
end

webpage/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

webpage/app/helpers/application_helper.rb
module ApplicationHelper
end

webpage/app/helpers/reviews_helper.rb
module ReviewsHelper
end

webpage/app/helpers/welcome_helper.rb
module WelcomeHelper
end

webpage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

webpage/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br>
    <%= f.text_field :picture_url %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webpage/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

webpage/app/views/reviews/index.html.erb
<div class="row">

<h1>Welcome to my Travel Guide.</h1>
<p>This website allows you to have more knowledge about othetr countries around you and their beautiful nature. </p>


<h3>Reviews</h3>


<br>

<% @reviews.each do |review| %>

  <div class="row">
    <div class="small-6 large-5 columns">
      <img class="th" src=<%= review.picture_url %> width="598"/>
    </div>
    <div class="small-6 large-7 columns">
      <h1><%= review.location %></h1>
      <p><%= review.description %></p>
      </div>
    </div>
    <hr>
  <% end %>

<%= link_to 'New Review', new_review_path, class: "button"  %>

<hr>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
    <tr>
      <td><%= review.location %></td>
      <td><%= link_to 'Show', review %></td>
      <td><%= link_to 'Edit', edit_review_path(review) %></td>
      <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

webpage/app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

webpage/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @review.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @review.video_url %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @review.picture_url %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

webpage/app/views/welcome/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Foundation | Welcome</title>
  <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>
<body>

  <div class="top-bar">
    <div class="row">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Senjuti Saha</li>
          <li class="has-submenu">
            <a href="#">One</a>
            <ul class="submenu menu vertical" data-submenu>
              <li><a href="#">One</a></li>
              <li><a href="#">Two</a></li>
              <li><a href="#">Three</a></li>
            </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="medium-6 columns">
      <img class="thumbnail" src=http://tedytravel.com/wp-content/uploads/2016/04/Krabi-10-672x372.jpg>
      <div class="row small-up-4">
        <div class="column" style="width: 23%; height: 163px">
          <img height="221" src="http://cdn.ek.aero/english/images/Phuket_tcm233-2256631.jpg" width="369">
        </div>
        <div class="column"style="width: 23%; height: 163px">
          <img height="178" src="http://www.simonsholidays.in/wp-content/uploads/2014/09/Amazing-Bagnkok.jpg" width="330">
        </div>
        <div class="column"style="width: 23%; height: 163px">
          <img height="178" src="http://louisianaconsularcorps.com/wp-content/gallery/thailand/thailand-bangkok.jpg" width="330">
        </div>
        <div class="column"style="width: 23%; height: 163px">
          <img height="178" src="http://foundtheworld.com/wp-content/uploads/2014/07/Ko-Phi-Phi-4.jpg" width="330">
        </div>
      </div>
    </div>
    <div class="medium-6 large-5 columns">
      <h3>Welcome to my Travel Guide.</h3>
      <p>This website allows you to have more knowledge about othetr countries around you and their beautiful nature. </p>


      <div class="small secondary expanded button-group">

        <div class="small secondary expanded button-group">
          <a href="http://www.facbook.com" class="button">Facebook</a>
          <a href="http://www.twitter.com" class="button">Twitter</a>
          <a href="http://www.youtube.com" class="button">Youtube</a>

      </div>
    </div>
  </div>
  <div class="column row">
    <hr>
    <div class="tabs-content" data-tabs-content="example-tabs">
      <div class="tabs-panel is-active" id="panel1">
        <h4>&nbsp;</h4>
        <h4>Reviews</h4>
        <div class="media-object stack-for-small">
          <div class="media-object-section">
            <img class="thumbnail" src="http://kindertravelguide.com/wp-content/uploads/2015/11/italian-riviera1-slide1.jpg" width="598"/>
          </div>
          <div class="media-object-section">
            <h1>ITALY</h1>
            <p>if what you are looking for is a unique and memorable experience that will
              give you the opportunity to learn about another culture through art, cultural
              events, historical cites, and archeological treasures, a place to visit is
              certainly Italy. Among many places in the world where you can relive the past,
              Italy is certainly the most charming place. This little country in the middle of
              the Mediterranean represents the cradle of the Roman Empire and the Renaissance,
              and offers an incredible number of opportunities for people eager to learn about
              an ancient civilization that shaped the history of many cultures</p>
            </div>
          </div>
          <div class="media-object stack-for-small">
            <div class="media-object-section">
              <img src="http://science-all.com/images/egypt/egypt-04.jpg">
            </div>
            <div class="media-object-section">
              <h1>EGYPT</h1>
              <p>
                Ancient Egypt is a wonderful land of mystery. People today still have no idea
                how to duplicate some of the achievements of Ancient Egyptians. Egypt became a
                great civilization due to many things, but there were three that seem to stand
                out above the rest. They were the geography, culture, and Architecture.Egypt can be divided into four major regions: the Nile Valley and Delta, the
                Arabian Desert, the Libyan Desert, and the Sinai. The Nile River valley is about
                950 mi. long. In the south the valley is rarely more than 2 mi. wide.</p>
              </div>
            </div>
            <div class="media-object stack-for-small">
              <div class="media-object-section">
                <img height="303" src="http://www.timeforkids.com/files/styles/tfk_rect_large/public/2011-07/france_ss2.jpg?itok=aW-EM84A" width="617">
              </div>
              <div class="media-object-section">
                <h1>FRANCE</h1>
                <p>
                  <span style="color: rgb(51, 51, 51); font-family: Arial, Helvetica; font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 26px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
                    France, which is the largest nation in Western Europe, is a presidential
                    republic.&nbsp; France is a very important nation in Europe and it continues to be
                    involved in contemporary policy issues.&nbsp; Helping the world as one of the great
                    trading nations, France is a very important trading partner with the United
                    States.&nbsp;</span><span id="more-76" style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: Arial, Helvetica; font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 26px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"></span><span style="color: rgb(51, 51, 51); font-family: Arial, Helvetica; font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 26px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">&nbsp;Not
                      only is France important to the United States, they are also important to
                      countries all over the world.&nbsp; Their abundance of both mineral and agricultural
                      resources make them a very important supplier of products all over the world.&nbsp; I
                      chose to report on France because it is an interesting county and I wanted to
                      learn more about it.</span></p>
                    </div>
                  </div>
                  <label>
                    My Review
                    <textarea placeholder="None"></textarea>
                  </label>
                  <button class="button">Submit Review</button>
                </div>
                <div class="tabs-panel" id="panel2">
                  <div class="row medium-up-3 large-up-5">
                    <div class="column">
                      <img class="thumbnail" src="http://placehold.it/350x200">
                      <h5>Other Product <small>$22</small></h5>
                      <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
                      <a href="#" class="button hollow tiny expanded">Buy Now</a>
                    </div>
                    <div class="column">
                      <img class="thumbnail" src="http://placehold.it/350x200">
                      <h5>Other Product <small>$22</small></h5>
                      <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
                      <a href="#" class="button hollow tiny expanded">Buy Now</a>
                    </div>
                    <div class="column">
                      <img class="thumbnail" src="http://placehold.it/350x200">
                      <h5>Other Product <small>$22</small></h5>
                      <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
                      <a href="#" class="button hollow tiny expanded">Buy Now</a>
                    </div>
                    <div class="column">
                      <img class="thumbnail" src="http://placehold.it/350x200">
                      <h5>Other Product <small>$22</small></h5>
                      <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>
                      <a href="#" class="button hollow tiny expanded">Buy Now</a>
                    </div>
                    <div class="column">
                      <img class="thumbnail" src="http://placehold.it/350x200">
                      <h5>Other Product <small>$22</small></h5>
                      <p>In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla, orci ac euismod semper, magna diam.</p>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row column">
              <hr>
              <ul class="menu">
                <li>Senjuti Saha</li>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
                <li class="float-right">Copyright 2016</li>
              </ul>
            </div>
            <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
            <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
            <script>
              $(document).foundation();
            </script>
          </body>
          </html>


\\rails g scaffold review title:string description:text picture_url:string